### ISSUE TITLE
Proposal: Border radius

### ISSUE THREAD

**Issue by KSXGitHub** [mupchrch/outline-selection#10]

**Comment by KSXGitHub** [comment]
I want to create a pull request but your package is written solely in JavaScript so I don't know how to make it 😄 

Anyway, I already found a solution, this is my `styles.less`

``` less
atom-text-editor, atom-text-editor::shadow {
  @border-radius: @outline-selection-border-radius;
  .outline-selection {
    .outline-selection-left {
      border-top-left-radius: @border-radius;
      border-bottom-left-radius: @border-radius;
    }
    .outline-selection-top {
      border-top-left-radius: @border-radius;
      border-top-right-radius: @border-radius;
    }
    .outline-selection-right {
      border-top-right-radius: @border-radius;
      border-bottom-right-radius: @border-radius;
    }
    .outline-selection-bottom {
      border-bottom-left-radius: @border-radius;
      border-bottom-right-radius: @border-radius;
    }
  }
}
```

And this is the result
![image](https://cloud.githubusercontent.com/assets/11488886/18814725/25a33d2a-8346-11e6-9079-121af009d146.png)
